image:
  repository: ghcr.io/gethomepage/homepage
  tag: v0.7.4@sha256:84d3b6d260bd1ed4b04a3671bacd6d933662cfd07f8ccc312fbdf2182fa3d97a
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10352
        protocol: http
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: /app/config
portal:
  open:
    enabled: true

serviceAccount:
  main:
    enabled: true
    primary: true

rbac:
  main:
    enabled: true
    primary: true
    clusterWide: true
    rules:
      - apiGroups:
          - ""
        resources:
          - namespaces
          - pods
          - nodes
        verbs:
          - get
          - list
      - apiGroups:
          - extensions
          - networking.k8s.io
        resources:
          - ingresses
        verbs:
          - get
          - list
      - apiGroups:
          - traefik.containo.us
          - traefik.io
        resources:
          - ingressroutes
        verbs:
          - get
          - list
      - apiGroups:
          - metrics.k8s.io
        resources:
          - nodes
          - pods
        verbs:
          - get
          - list
      - apiGroups:
          - apiextensions.k8s.io
        resources:
          - customresourcedefinitions/status
        verbs:
          - get
workload:
  main:
    podSpec:
      automountServiceAccountToken: true
